const products = [
  /*https://poklonducan.rs/zenska-luca-barra-mindjusa-od-hirurskog-celika-ok1162.html*/
    {
      id: 1,
      title: 'ŽENSKI VICTORIA CRUZ LIS VIOLET LANČIĆ SA SWAROVSKI LJUBIČASTIM KRISTALOM',
      category: 'lančići',
      price: 4200,
      img: './images/l-1.jpg',
      desc: `Ženski victoria cruz lis violet lančić sa swarovski ljubičastim kristalom `,
    },
    {
      id: 2,
      title: 'ŽENSKI VICTORIA CRUZ MACEDONIA SIMPLE LIGHT SAPPHIRE LANČIĆ',
      category: 'lančići',
      price: 4200 ,
      img: './images/l-2.jpg',
      desc: `Ženski victoria cruz macedonia simple light sapphire lančić    `,
    },
    {
      id: 3,
      title: 'ŽENSKI OLIVER WEBER PACE 925AG ZIRCON LANČIĆ SA SWAROVSKI KRISTALIMA',
      category: 'lančići',
      price: 5990,
      img: './images/l-3.jpg',
      desc: `Ženski oliver weber pace 925ag zircon lančić sa swarovski kristalima`,
    },
    {
      id: 4,
      title: 'ŽENSKA LUCA BARRA MINDJUŠA OD HIRURŠKOG ČELIKA',
      category: 'minđuše',
      price: 630,
      img: './images/m-1.jpg',
      desc: `Ženska luca barra mindjuša od hirurškog čelika `,
    },
    {
      id: 5,
      title: 'Ženske Victoria Cruz Macedonia Simple Violet Mindjuše Sa Swarovski Ljubičastim Kristalom',
      category: 'minđuše',
      price:  1920,
      img: './images/m-2.jpg',
      desc: `Ženske Victoria Cruz Macedonia Simple Violet Mindjuše Sa Swarovski Ljubičastim Kristalom`,
    },
    {
      id: 6,
      title: 'ŽENSKE FREELOOK ROZE ZLATNE MINDJUŠE OD HIRURŠKOG ČELIKA',
      category: 'minđuše',
      price: 1590,
      img: './images/m-3.jpg',
      desc: `Ženske freelook roze zlatne mindjuše od hirurškog čelika`,

    },
    {
      id: 7,
      title: 'ŽENSKA FREELOOK SREBRNA NARUKVICA OD HIRURŠKOG ČELIKA',
      category: 'narukvice',
      price: 990,
      img: './images/n-1.jpg',
      desc: `Ženska freelook srebrna narukvica od hirurškog čelika `,
     
    },
    {
      id: 8,
      title: 'ŽENSKA FREELOOK SREBRNA NARUKVICA OD HIRURŠKOG ČELIKA',
      category: 'narukvice',
      price: 1400,
      img: './images/n-2.jpg',
      desc: `Ženska freelook srebrna narukvica od hirurškog čelika `,
      
    },
    {
      id: 9,
      title: 'ŽENSKA FREELOOK ROZE ZLATNA NARUKVICA OD HIRURŠKOG ČELIKA',
      category: 'narukvice',
      price: 1360,
      img: './images/n-3.jpg',
      desc: `Ženska freelook zlatna narukvica od hirurškog čelika`,
      
    },
    {
      id: 10,
      title: 'ŽENSKA FREELOOK SREBRNA OGRLICA OD HIRURŠKOG ČELIKA',
      category: 'ogrlice',
      price: 2000,
      img: './images/o-1.jpg',
      desc: `Ženska freelook srebrna ogrlica od hirurškog čelika `,
    },
    {
      id: 11,
      title: 'ŽENSKA PD PAOLA DAISY SREBRNA OGRLICA',
      category: 'ogrlice',
      price: 7800,
      img: './images/o-2.jpg',
      desc: `Ženska pd paola daisy srebrna ogrlica `,
    
    },
    {
      id: 12,
      title: 'ŽENSKA PD PAOLA MINI CROWN SREBRNA OGRLICA',
      category: 'ogrlice',
      price: 7000,
      img: './images/o-3.jpg',
      desc: `Ženska pd paola mini crown srebrna ogrlica`,
     
    },
    {
      id: 13,
      title: 'ŽENSKI PD PAOLA CRUISE SREBRNI PRSTEN SA BELIM CIRKONIMA',
      category: 'prstenje',
      price: 11800,
      img: './images/p-1.jpg',
      desc: `Ženski pd paola cruise srebrni prsten sa belim cirkonima`,
    },
    {
      id: 14,
      title: 'ŽENSKI PD PAOLA SISI SREBRNI PRSTEN SA BELIM CIRKONIMA',
      category: 'prstenje',
      price: 7800,
      img: './images/p-2.jpg',
      desc: `Ženski pd paola sisi srebrni prsten sa belim cirkonima `,
    },
    {
      id: 15,
      title: 'ŽENSKI PD PAOLA COUPLET ZLATNI PRSTEN SA POZLATOM 18k',
      category: 'prstenje',
      price: 4600,
      img: './images/p-3.jpg',
      desc: `Ženski pd paola couplet zlatni prsten sa pozlatom 18k`,
    },
  ];
  export default products;